name: Build

on:
  workflow_call:
    inputs:
      publish:
        required: true
        type: boolean
      version:
        required: true
        type: string

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: microsoft/setup-msbuild@v2
      - name: Build binaries
        env:
          XZ_VERSION: ${{ inputs.version }}
        run: |
          . scripts/build.ps1
      - name: Pack binaries
        if: ${{ inputs.publish }}
        env:
          XZ_VERSION: ${{ inputs.version }}
        run: |
          . scripts/pack.ps1
      - name: GitHub Release
        if: ${{ inputs.publish }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "artifacts/*.zip"
          bodyFile: README.md
          name: ${{ inputs.version }}
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
