name: Build on push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
      - uses: microsoft/setup-msbuild@v1
      - name: Get latest tag
        id: get-tag
        run: |
          $(git describe --tags) -Replace '^v', 'version=' >> $env:GITHUB_OUTPUT
      - name: Build and pack package
        env:
          XZ_VERSION: ${{ steps.get-tag.outputs.version }}
        run: |
          nuget restore
          Push-Location -Path "NitroPatcher"
          Move-Item -Path "Properties/AssemblyInfo.cs" -Destination "Properties/AssemblyInfo.cs.bak"
          Get-Content -Path "Properties/AssemblyInfo.cs.bak" -Encoding UTF8 | ForEach-Object { $_ -Replace '(Assembly(?:File)?Version)\("[\d\.]+"\)', "`$1(""$env:XZ_VERSION"")" } | Out-File -FilePath "Properties/AssemblyInfo.cs" -Encoding UTF8
          Move-Item -Path "MainWindow.xaml" -Destination "MainWindow.xaml.bak"
          Get-Content -Path "MainWindow.xaml.bak" -Encoding UTF8 | ForEach-Object { $_ -Replace '(版本：)[\d\.]+', "版本：$env:XZ_VERSION" } | Out-File -FilePath "MainWindow.xaml" -Encoding UTF8
          msbuild /p:Configuration=Release /p:TargetFramework=net47 /p:OutDir="../artifacts" /verbosity:minimal
          Remove-Item -Path "Properties/AssemblyInfo.cs"
          Move-Item -Path "Properties/AssemblyInfo.cs.bak" -Destination "Properties/AssemblyInfo.cs"
          Remove-Item -Path "MainWindow.xaml"
          Move-Item -Path "MainWindow.xaml.bak" -Destination "MainWindow.xaml"
          Compress-Archive -Path "../artifacts/NitroPatcher.exe" -DestinationPath "../artifacts/NitroPatcher.${env:XZ_VERSION}.zip"
          Pop-Location
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "artifacts/NitroPatcher.*.zip"
          bodyFile: README.md
          name: "v${{ steps.get-tag.outputs.version }}"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
